#!/usr/bin/env python3
"""Regenerate the Featured Insights grid on index.html.

Shows only articles published in the current month or the one before it, newest
first. Run it at the start of each month (or in CI) so the homepage stops
advertising stale guides.

    python3 scripts/build_featured_insights.py          # rewrite index.html
    python3 scripts/build_featured_insights.py --check  # exit 1 if out of date

Filtering uses datePublished, not dateModified: a past bulk edit left most
articles sharing one dateModified, which would drag the whole archive in.
"""
import re, glob, html, sys, os
from datetime import date

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
START = "<!-- FEATURED-INSIGHTS:START (generated by scripts/build_featured_insights.py) -->"
END = "<!-- FEATURED-INSIGHTS:END -->"
MONTHS = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sept","Oct","Nov","Dec"]


def prev_month(y, m):
    return (y - 1, 12) if m == 1 else (y, m - 1)


def collect(today):
    keep = {f"{today.year:04d}-{today.month:02d}"}
    py, pm = prev_month(today.year, today.month)
    keep.add(f"{py:04d}-{pm:02d}")

    out = []
    for f in sorted(glob.glob(os.path.join(ROOT, "blog", "*.html"))):
        s = open(f, encoding="utf-8", errors="ignore").read()
        if 'http-equiv="refresh"' in s:      # redirect stub, not an article
            continue
        dp = re.search(r'"datePublished":"([^"]+)"', s)
        dm = re.search(r'"dateModified":"([^"]+)"', s)
        pub = (dp or dm)
        if not pub:
            continue
        pub = pub.group(1)[:10]
        if pub[:7] not in keep:
            continue
        t = re.search(r"<title>(.*?)</title>", s, re.S)
        d = re.search(r'<meta name="description" content="([^"]*)"', s)
        tag = re.search(r'<span class="tag"[^>]*>([^<·]+)', s)
        title = re.sub(r"\s*\|\s*MoneyMindTool\s*$", "",
                       re.sub(r"\s+", " ", t.group(1)).strip()) if t else ""
        out.append({
            "pub": pub,
            "mod": dm.group(1)[:10] if dm else pub,
            "href": "blog/" + os.path.basename(f),
            "title": title,
            "desc": (d.group(1) if d else "").strip(),
            "cat": (tag.group(1).strip() if tag else "Guide"),
        })
    out.sort(key=lambda r: (r["pub"], r["mod"]), reverse=True)
    return out


def render(rows):
    lines = [START, '        <section class="mm-blog-grid">']
    for r in rows:
        # An article rewritten later than it was published should say so, rather
        # than advertising the older date on a "recent updates" shelf.
        shown = max(r["pub"], r["mod"])
        y, m, _ = shown.split("-")
        stamp = f"{MONTHS[int(m) - 1]} {y}"
        if r["mod"] > r["pub"]:
            stamp = "Updated " + stamp
        lines += [
            '            <article class="mm-blog-card">',
            f'                <span class="tag">{html.escape(r["cat"])} · {stamp}</span>',
            f'                <h3>{r["title"]}</h3>',
            f'                <p>{r["desc"]}</p>',
            f'                <a href="{r["href"]}">Read more &rarr;</a>',
            "            </article>",
        ]
    lines += ["        </section>", "        " + END]
    return "\n".join(lines)


def main():
    check = "--check" in sys.argv
    idx = os.path.join(ROOT, "index.html")
    s = open(idx, encoding="utf-8").read()
    rows = collect(date.today())
    if not rows:
        print("no articles in the current or previous month - leaving index.html alone")
        return 0
    block = render(rows)
    if START in s and END in s:
        new = re.sub(re.escape(START) + r".*?" + re.escape(END), block, s, flags=re.S)
    else:  # first run: replace the existing hand-written grid
        m = re.search(r'<section class="mm-blog-grid">.*?</section>', s, re.S)
        if not m:
            print("could not find the blog grid in index.html", file=sys.stderr)
            return 2
        new = s[: m.start()] + block.lstrip() + s[m.end():]
    if new == s:
        print(f"Featured Insights already current ({len(rows)} articles)")
        return 0
    if check:
        print(f"Featured Insights is STALE - {len(rows)} articles should be shown", file=sys.stderr)
        return 1
    open(idx, "w", encoding="utf-8").write(new)
    print(f"Featured Insights rebuilt with {len(rows)} article(s):")
    for r in rows:
        print(f"   {r['pub']}  {r['title'][:60]}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
